### PR TITLE
Feature/added time picker

### PR DESCRIPTION
**Pull request by danish1994**
## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Description
Describe your pr here.
Added option for time picker within the existing component, which under a flag of "showTime"

Screenshot 2020-02-06 at 5 13 51 PM

> Related Issue: #4

### CODE REVIEW

**Comment by kenjoegolo** [comment]
is this being ignored by the author?

**Comment by kenjoegolo** [comment]
I need this feature :D

**Comment by RonHouben** [comment]
@danish1994 thanks so much for this, I need it too.
Would be great if your PR finally gets merged :)!

danish1994:feature/addedTimePicker

**Comment by davidsu06** [comment]
Hi, did this got merged?

**Comment by alimovz** [comment]
This is a great addition. So this has not been merged and isn't part of the lib. But can I still use it? And if so, how?

**Comment by joeyparis** [comment]
Can this be reopened? I'm definitely interested in its addition.

**Comment by sdabhi23** [comment]
@danish1994 is this feature complete? If not, what needs to be done to complete it? Would be happy to contribute, as I really need this feature

**Comment by danish1994** [comment]
@sdabhi23 - I think the implementation was quite old. So I would say, it would be better if we can reiterate on the implementation and then raise the PR.

**Pull request closed without merging**
